#args.py
import argparse

parser = argparse.ArgumentParser(description='')
parser.add_argument('--vis_train_dir', default=r'RoadScene/crop_LR_visible', type=str)
parser.add_argument('--ir_train_dir', default=r'RoadScene/cropinfrared', type=str)
# parser.add_argument('--vis_test_dir', default=r'vis', type=str)
# parser.add_argument('--ir_test_dir', default=r'ir', type=str)
parser.add_argument('--vis_test_dir', default=r'RoadScene/crop_LR_visible', type=str)
parser.add_argument('--ir_test_dir', default=r'RoadScene/cropinfrared', type=str)
# parser.add_argument('--vis_test_dir', default=r'test_results1/20260319_15-47-06_DenoiseReg-OBRT-CrossGate-C2RFColorStyle-Test_epoch9999_iter56_synthetic_eval/paper_vis/FLIR_07225/vis_rgb.png', type=str)
# parser.add_argument('--ir_test_dir', default=r'test_results1/20260319_15-47-06_DenoiseReg-OBRT-CrossGate-C2RFColorStyle-Test_epoch9999_iter56_synthetic_eval/paper_vis/FLIR_07225/ir_deformed_or_input.png', type=str)
parser.add_argument('--test_model_path', type=str, default='train_modelsgaijin/20260313_16-09-51_DenoiseReg-OBRT-CrossGate-RegFirst-C2RFColorStyle_model/epoch9999_iter56.pth')
parser.add_argument('--test_save_dir', type=str, default='./test_results7')
parser.add_argument('--train_save_img_dir', default='imagesgaijin', type=str)
parser.add_argument('--train_save_model_dir', default='train_modelsgaijin', type=str)
parser.add_argument('--pretrain_model_dir', default='pretrain')
parser.add_argument('--save_image_num', dest='save_image_num', default=1, type=int)
parser.add_argument('--save_model_num', dest='save_model_num', default=10, type=int)
parser.add_argument('--img_size', type=int, default=256)
parser.add_argument('--small_w_size', type=int, default=16)
parser.add_argument('--large_w_size', type=int, default=28)
parser.add_argument('--batch_size', dest='batch_size', default=4, type=int)
parser.add_argument('--LR', type=float, default=0.0001)
parser.add_argument('--LR_target', type=float, default=0.001)
parser.add_argument('--Epoch', type=int, default=10000)
parser.add_argument('--Warm_epoch', type=int, default=160)
parser.add_argument('--dropout', type=float, default=0.1)
args = parser.parse_args()